# This is the Azure K8S cluster iaac pipeline for creating the cluster via Azure by executing the 
# terraform scripts via this yaml file we add scripts to execute our terraform scripts



trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:  
- script: echo K8S terraform Azure!
  displayName: 'Run a one-line script debug'

  # Inorder to use the secured file we need to first download that secured file from library
- task: DownloadSecureFile@1
  name: publickey 
  inputs:
    secureFile: 'azure_rsa.pub'
- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret)  -var ssh_public_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-manager-service-connection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageaccountkeninter'
    backendAzureRmContainerName: 'storageaccountkenintercontainer'
    backendAzureRmKey: 'kubernetes-dev.tfstate'
    allowTelemetryCollection: true

